using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using UniCli.SourceGenerator.Analysis;

namespace UniCli.SourceGenerator.Emitters
{
    internal static class InstanceMethodCommandEmitter
    {
        public static string EmitSetMethod(
            InstanceMethodInfo methodInfo,
            string typeFullName,
            SettingsCommandGenerator.ResolveMode resolveMode)
        {
            var sb = new StringBuilder();
            EmitHelper.AppendAutoGeneratedHeader(sb);
            EmitHelper.AppendUsings(sb);

            var method = methodInfo.Symbol;
            var commandName = $"{methodInfo.CommandPrefix}.{method.Name}";
            var className = commandName.Replace(".", "") + "Handler";
            var requestName = commandName.Replace(".", "") + "Request";
            var responseName = commandName.Replace(".", "") + "Response";

            var hasEnumParams = method.Parameters.Any(p =>
                TypeSerializabilityChecker.IsEnumType(p.Type));

            sb.AppendLine("namespace UniCli.Server.Editor.Handlers");
            sb.AppendLine("{");
            sb.AppendLine($"    public sealed class {className} : CommandHandler<{requestName}, {responseName}>");
            sb.AppendLine("    {");
            sb.AppendLine($"        public override string CommandName => \"{commandName}\";");
            sb.AppendLine($"        public override string Description => \"Call {typeFullName.Replace("global::", "")}.{method.Name}\";");
            sb.AppendLine();

            if (hasEnumParams)
            {
                EmitHelper.AppendParseEnumHelper(sb, "        ");
                sb.AppendLine();
            }

            sb.AppendLine($"        protected override ValueTask<{responseName}> ExecuteAsync({requestName} request)");
            sb.AppendLine("        {");

            EmitHelper.AppendInstanceResolveCode(sb, "            ", resolveMode, typeFullName);
            sb.AppendLine();

            var paramExprs = method.Parameters
                .Select(p => EmitHelper.GetParameterExpression(p, "request"))
                .ToArray();
            var paramList = string.Join(", ", paramExprs);

            sb.AppendLine($"            instance.{method.Name}({paramList});");

            EmitHelper.AppendSetDirty(sb, "            ");

            sb.AppendLine($"            return new ValueTask<{responseName}>(new {responseName}");
            sb.AppendLine("            {");
            sb.AppendLine("                success = true");
            sb.AppendLine("            });");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            // Request class
            sb.AppendLine("    [Serializable]");
            sb.AppendLine($"    public class {requestName}");
            sb.AppendLine("    {");
            EmitHelper.AppendInstanceResolveRequestFields(sb, "        ", resolveMode);
            foreach (var param in method.Parameters)
            {
                var fieldType = EmitHelper.GetRequestFieldType(param);
                sb.AppendLine($"        public {fieldType} {param.Name};");
            }
            sb.AppendLine("    }");
            sb.AppendLine();

            // Response class
            sb.AppendLine("    [Serializable]");
            sb.AppendLine($"    public class {responseName}");
            sb.AppendLine("    {");
            sb.AppendLine("        public bool success;");
            sb.AppendLine("    }");

            sb.AppendLine("}");
            return sb.ToString();
        }

        public static string EmitGetMethod(
            InstanceMethodInfo methodInfo,
            string typeFullName,
            SettingsCommandGenerator.ResolveMode resolveMode)
        {
            var sb = new StringBuilder();
            EmitHelper.AppendAutoGeneratedHeader(sb);
            EmitHelper.AppendUsings(sb);

            var method = methodInfo.Symbol;
            var commandName = $"{methodInfo.CommandPrefix}.{method.Name}";
            var className = commandName.Replace(".", "") + "Handler";
            var requestName = commandName.Replace(".", "") + "Request";
            var responseName = commandName.Replace(".", "") + "Response";

            var hasEnumParams = method.Parameters.Any(p =>
                TypeSerializabilityChecker.IsEnumType(p.Type));

            var returnIsEnum = TypeSerializabilityChecker.IsEnumType(method.ReturnType);
            var valueType = EmitHelper.GetResponseFieldType(method.ReturnType);

            sb.AppendLine("namespace UniCli.Server.Editor.Handlers");
            sb.AppendLine("{");
            sb.AppendLine($"    public sealed class {className} : CommandHandler<{requestName}, {responseName}>");
            sb.AppendLine("    {");
            sb.AppendLine($"        public override string CommandName => \"{commandName}\";");
            sb.AppendLine($"        public override string Description => \"Call {typeFullName.Replace("global::", "")}.{method.Name}\";");
            sb.AppendLine();

            if (hasEnumParams)
            {
                EmitHelper.AppendParseEnumHelper(sb, "        ");
                sb.AppendLine();
            }

            sb.AppendLine($"        protected override ValueTask<{responseName}> ExecuteAsync({requestName} request)");
            sb.AppendLine("        {");

            EmitHelper.AppendInstanceResolveCode(sb, "            ", resolveMode, typeFullName);
            sb.AppendLine();

            var paramExprs = method.Parameters
                .Select(p => EmitHelper.GetParameterExpression(p, "request"))
                .ToArray();
            var paramList = string.Join(", ", paramExprs);

            if (returnIsEnum)
            {
                sb.AppendLine($"            var result = instance.{method.Name}({paramList});");
                sb.AppendLine($"            return new ValueTask<{responseName}>(new {responseName}");
                sb.AppendLine("            {");
                sb.AppendLine("                value = result.ToString()");
                sb.AppendLine("            });");
            }
            else
            {
                sb.AppendLine($"            var result = instance.{method.Name}({paramList});");
                sb.AppendLine($"            return new ValueTask<{responseName}>(new {responseName}");
                sb.AppendLine("            {");
                sb.AppendLine("                value = result");
                sb.AppendLine("            });");
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            // Request class (always has at least guid/instanceId)
            sb.AppendLine("    [Serializable]");
            sb.AppendLine($"    public class {requestName}");
            sb.AppendLine("    {");
            EmitHelper.AppendInstanceResolveRequestFields(sb, "        ", resolveMode);
            foreach (var param in method.Parameters)
            {
                var fieldType = EmitHelper.GetRequestFieldType(param);
                sb.AppendLine($"        public {fieldType} {param.Name};");
            }
            sb.AppendLine("    }");
            sb.AppendLine();

            // Response class
            sb.AppendLine("    [Serializable]");
            sb.AppendLine($"    public class {responseName}");
            sb.AppendLine("    {");
            sb.AppendLine($"        public {valueType} value;");
            sb.AppendLine("    }");

            sb.AppendLine("}");
            return sb.ToString();
        }
    }
}
