using System.Text;
using Microsoft.CodeAnalysis;
using UniCli.SourceGenerator.Analysis;

namespace UniCli.SourceGenerator.Emitters
{
    internal static class InstanceInspectCommandEmitter
    {
        public static string Emit(InstanceTypeInfo info)
        {
            var sb = new StringBuilder();
            EmitHelper.AppendAutoGeneratedHeader(sb);
            EmitHelper.AppendUsings(sb);

            var className = info.CommandPrefix.Replace(".", "") + "InspectHandler";
            var requestName = info.CommandPrefix.Replace(".", "") + "InspectRequest";
            var responseName = info.CommandPrefix.Replace(".", "") + "InspectResponse";
            var typeFullName = info.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            sb.AppendLine("namespace UniCli.Server.Editor.Handlers");
            sb.AppendLine("{");

            // Handler class
            sb.AppendLine($"    public sealed class {className} : CommandHandler<{requestName}, {responseName}>");
            sb.AppendLine("    {");
            sb.AppendLine($"        public override string CommandName => \"{info.CommandPrefix}.Inspect\";");
            sb.AppendLine($"        public override string Description => \"Inspect {info.CommandPrefix} instance\";");
            sb.AppendLine();
            sb.AppendLine($"        protected override ValueTask<{responseName}> ExecuteAsync({requestName} request, CancellationToken cancellationToken)");
            sb.AppendLine("        {");

            EmitHelper.AppendInstanceResolveCode(sb, "            ", info.ResolveMode, typeFullName);
            sb.AppendLine();

            sb.AppendLine($"            var response = new {responseName}();");

            foreach (var prop in info.Properties)
            {
                if (prop.Symbol.GetMethod == null) continue;
                var fieldName = EmitHelper.ToCamelCase(prop.PascalCaseName);
                var readExpr = prop.IsEnum
                    ? $"instance.{prop.Symbol.Name}.ToString()"
                    : $"instance.{prop.Symbol.Name}";
                sb.AppendLine($"            try {{ response.{fieldName} = {readExpr}; }}");
                sb.AppendLine("            catch (System.Exception) { }");
            }

            sb.AppendLine($"            return new ValueTask<{responseName}>(response);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            // Request class
            sb.AppendLine("    [Serializable]");
            sb.AppendLine($"    public class {requestName}");
            sb.AppendLine("    {");
            EmitHelper.AppendInstanceResolveRequestFields(sb, "        ", info.ResolveMode);
            sb.AppendLine("    }");
            sb.AppendLine();

            // Response class
            sb.AppendLine("    [Serializable]");
            sb.AppendLine($"    public class {responseName}");
            sb.AppendLine("    {");

            foreach (var prop in info.Properties)
            {
                if (prop.Symbol.GetMethod == null) continue;
                var fieldType = EmitHelper.GetResponseFieldType(prop.Symbol.Type);
                var fieldName = EmitHelper.ToCamelCase(prop.PascalCaseName);
                sb.AppendLine($"        public {fieldType} {fieldName};");
            }

            sb.AppendLine("    }");

            sb.AppendLine("}");
            return sb.ToString();
        }
    }
}
