using System.Text;
using Microsoft.CodeAnalysis;
using UniCli.SourceGenerator.Analysis;

namespace UniCli.SourceGenerator.Emitters
{
    internal static class InstanceSetPropertyCommandEmitter
    {
        public static string Emit(
            InstancePropertyInfo property,
            string typeFullName,
            SettingsCommandGenerator.ResolveMode resolveMode)
        {
            var sb = new StringBuilder();
            EmitHelper.AppendAutoGeneratedHeader(sb);
            EmitHelper.AppendUsings(sb);

            var commandName = $"{property.CommandPrefix}.Set{property.PascalCaseName}";
            var className = commandName.Replace(".", "") + "Handler";
            var requestName = commandName.Replace(".", "") + "Request";
            var responseName = commandName.Replace(".", "") + "Response";

            var valueType = EmitHelper.GetResponseFieldType(property.Symbol.Type);

            sb.AppendLine("namespace UniCli.Server.Editor.Handlers");
            sb.AppendLine("{");

            sb.AppendLine($"    public sealed class {className} : CommandHandler<{requestName}, {responseName}>");
            sb.AppendLine("    {");
            sb.AppendLine($"        public override string CommandName => \"{commandName}\";");
            sb.AppendLine($"        public override string Description => \"Set {property.CommandPrefix}.{property.Symbol.Name}\";");
            sb.AppendLine();

            if (property.IsEnum)
            {
                EmitHelper.AppendParseEnumHelper(sb, "        ");
                sb.AppendLine();
            }

            sb.AppendLine($"        protected override ValueTask<{responseName}> ExecuteAsync({requestName} request)");
            sb.AppendLine("        {");

            EmitHelper.AppendInstanceResolveCode(sb, "            ", resolveMode, typeFullName);
            sb.AppendLine();

            // Read previous value
            var readExpr = property.IsEnum
                ? $"instance.{property.Symbol.Name}.ToString()"
                : $"instance.{property.Symbol.Name}";
            sb.AppendLine($"            var previousValue = {readExpr};");

            // Assign new value
            if (property.IsEnum)
            {
                var enumFullName = property.Symbol.Type.ToDisplayString(
                    SymbolDisplayFormat.FullyQualifiedFormat);
                sb.AppendLine($"            instance.{property.Symbol.Name} = ParseEnum<{enumFullName}>(request.value, \"value\");");
            }
            else
            {
                sb.AppendLine($"            instance.{property.Symbol.Name} = request.value;");
            }

            EmitHelper.AppendSetDirty(sb, "            ");

            sb.AppendLine($"            var currentValue = {readExpr};");
            sb.AppendLine($"            return new ValueTask<{responseName}>(new {responseName}");
            sb.AppendLine("            {");
            sb.AppendLine("                previousValue = previousValue,");
            sb.AppendLine("                currentValue = currentValue");
            sb.AppendLine("            });");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            // Request class
            sb.AppendLine("    [Serializable]");
            sb.AppendLine($"    public class {requestName}");
            sb.AppendLine("    {");
            EmitHelper.AppendInstanceResolveRequestFields(sb, "        ", resolveMode);
            sb.AppendLine($"        public {valueType} value;");
            sb.AppendLine("    }");
            sb.AppendLine();

            // Response class
            sb.AppendLine("    [Serializable]");
            sb.AppendLine($"    public class {responseName}");
            sb.AppendLine("    {");
            sb.AppendLine($"        public {valueType} previousValue;");
            sb.AppendLine($"        public {valueType} currentValue;");
            sb.AppendLine("    }");

            sb.AppendLine("}");
            return sb.ToString();
        }
    }
}
