using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using UniCli.SourceGenerator.Analysis;

namespace UniCli.SourceGenerator.Emitters
{
    internal static class MethodCommandEmitter
    {
        public static string EmitSetMethod(SettingsMethodInfo methodInfo, string settingsTypeFullName)
        {
            var sb = new StringBuilder();
            EmitHelper.AppendAutoGeneratedHeader(sb);
            EmitHelper.AppendUsings(sb);

            var method = methodInfo.Symbol;
            var commandName = $"{methodInfo.CommandPrefix}.{method.Name}";
            var className = commandName.Replace(".", "") + "Handler";
            var requestName = commandName.Replace(".", "") + "Request";
            var responseName = commandName.Replace(".", "") + "Response";

            var hasEnumParams = method.Parameters.Any(p =>
                TypeSerializabilityChecker.IsEnumType(p.Type));
            var hasNamedBuildTarget = method.Parameters.Any(p =>
                TypeSerializabilityChecker.GetFullMetadataName(p.Type) ==
                "UnityEditor.Build.NamedBuildTarget");

            sb.AppendLine("namespace UniCli.Server.Editor.Handlers");
            sb.AppendLine("{");

            if (methodInfo.IsObsolete)
                sb.AppendLine("    [Obsolete]");

            sb.AppendLine($"    public sealed class {className} : CommandHandler<{requestName}, {responseName}>");
            sb.AppendLine("    {");
            sb.AppendLine($"        public override string CommandName => \"{commandName}\";");
            sb.AppendLine($"        public override string Description => \"Call {settingsTypeFullName.Replace("global::", "")}.{method.Name}\";");
            sb.AppendLine();

            if (hasEnumParams)
            {
                EmitHelper.AppendParseEnumHelper(sb, "        ");
                sb.AppendLine();
            }

            sb.AppendLine($"        protected override ValueTask<{responseName}> ExecuteAsync({requestName} request)");
            sb.AppendLine("        {");

            // Build parameter list
            var paramExprs = method.Parameters
                .Select(p => EmitHelper.GetParameterExpression(p, "request"))
                .ToArray();
            var paramList = string.Join(", ", paramExprs);

            sb.AppendLine($"            {settingsTypeFullName}.{method.Name}({paramList});");
            sb.AppendLine($"            return new ValueTask<{responseName}>(new {responseName}");
            sb.AppendLine("            {");
            sb.AppendLine("                success = true");
            sb.AppendLine("            });");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            // Request class
            sb.AppendLine("    [Serializable]");
            sb.AppendLine($"    public class {requestName}");
            sb.AppendLine("    {");
            foreach (var param in method.Parameters)
            {
                var fieldType = EmitHelper.GetRequestFieldType(param);
                sb.AppendLine($"        public {fieldType} {param.Name};");
            }
            sb.AppendLine("    }");
            sb.AppendLine();

            // Response class
            sb.AppendLine("    [Serializable]");
            sb.AppendLine($"    public class {responseName}");
            sb.AppendLine("    {");
            sb.AppendLine("        public bool success;");
            sb.AppendLine("    }");

            sb.AppendLine("}");
            return sb.ToString();
        }

        public static string EmitGetMethod(SettingsMethodInfo methodInfo, string settingsTypeFullName)
        {
            var sb = new StringBuilder();
            EmitHelper.AppendAutoGeneratedHeader(sb);
            EmitHelper.AppendUsings(sb);

            var method = methodInfo.Symbol;
            var commandName = $"{methodInfo.CommandPrefix}.{method.Name}";
            var className = commandName.Replace(".", "") + "Handler";
            var responseName = commandName.Replace(".", "") + "Response";

            var hasParams = method.Parameters.Length > 0;
            var requestName = hasParams
                ? commandName.Replace(".", "") + "Request"
                : "Unit";

            var hasEnumParams = method.Parameters.Any(p =>
                TypeSerializabilityChecker.IsEnumType(p.Type));
            var hasNamedBuildTarget = method.Parameters.Any(p =>
                TypeSerializabilityChecker.GetFullMetadataName(p.Type) ==
                "UnityEditor.Build.NamedBuildTarget");

            var returnIsEnum = TypeSerializabilityChecker.IsEnumType(method.ReturnType);
            var valueType = EmitHelper.GetResponseFieldType(method.ReturnType);

            sb.AppendLine("namespace UniCli.Server.Editor.Handlers");
            sb.AppendLine("{");

            if (methodInfo.IsObsolete)
                sb.AppendLine("    [Obsolete]");

            sb.AppendLine($"    public sealed class {className} : CommandHandler<{requestName}, {responseName}>");
            sb.AppendLine("    {");
            sb.AppendLine($"        public override string CommandName => \"{commandName}\";");
            sb.AppendLine($"        public override string Description => \"Call {settingsTypeFullName.Replace("global::", "")}.{method.Name}\";");
            sb.AppendLine();

            if (hasEnumParams)
            {
                EmitHelper.AppendParseEnumHelper(sb, "        ");
                sb.AppendLine();
            }

            sb.AppendLine($"        protected override ValueTask<{responseName}> ExecuteAsync({requestName} request)");
            sb.AppendLine("        {");

            var paramExprs = method.Parameters
                .Select(p => EmitHelper.GetParameterExpression(p, "request"))
                .ToArray();
            var paramList = string.Join(", ", paramExprs);

            if (returnIsEnum)
            {
                sb.AppendLine($"            var result = {settingsTypeFullName}.{method.Name}({paramList});");
                sb.AppendLine($"            return new ValueTask<{responseName}>(new {responseName}");
                sb.AppendLine("            {");
                sb.AppendLine("                value = result.ToString()");
                sb.AppendLine("            });");
            }
            else
            {
                sb.AppendLine($"            var result = {settingsTypeFullName}.{method.Name}({paramList});");
                sb.AppendLine($"            return new ValueTask<{responseName}>(new {responseName}");
                sb.AppendLine("            {");
                sb.AppendLine("                value = result");
                sb.AppendLine("            });");
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            // Request class (only if there are parameters)
            if (hasParams)
            {
                sb.AppendLine("    [Serializable]");
                sb.AppendLine($"    public class {requestName}");
                sb.AppendLine("    {");
                foreach (var param in method.Parameters)
                {
                    var fieldType = EmitHelper.GetRequestFieldType(param);
                    sb.AppendLine($"        public {fieldType} {param.Name};");
                }
                sb.AppendLine("    }");
                sb.AppendLine();
            }

            // Response class
            sb.AppendLine("    [Serializable]");
            sb.AppendLine($"    public class {responseName}");
            sb.AppendLine("    {");
            sb.AppendLine($"        public {valueType} value;");
            sb.AppendLine("    }");

            sb.AppendLine("}");
            return sb.ToString();
        }
    }
}
