using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using UniCli.SourceGenerator.Analysis;

namespace UniCli.SourceGenerator.Emitters
{
    internal static class NamedBuildTargetHelperEmitter
    {
        public static string Emit(INamedTypeSymbol namedBuildTargetType)
        {
            var sb = new StringBuilder();
            EmitHelper.AppendAutoGeneratedHeader(sb);

            sb.AppendLine("using UnityEditor.Build;");
            sb.AppendLine("using UniCli.Server.Editor.Handlers;");
            sb.AppendLine();

            sb.AppendLine("namespace UniCli.Server.Editor.Handlers");
            sb.AppendLine("{");
            sb.AppendLine("    internal static class NamedBuildTargetHelper");
            sb.AppendLine("    {");
            sb.AppendLine("        public static NamedBuildTarget Parse(string value)");
            sb.AppendLine("        {");
            sb.AppendLine("            switch (value)");
            sb.AppendLine("            {");

            // Find all public static readonly NamedBuildTarget properties/fields
            var targets = CollectStaticTargets(namedBuildTargetType);
            foreach (var target in targets)
            {
                sb.AppendLine($"                case \"{target}\": return NamedBuildTarget.{target};");
            }

            sb.AppendLine("                default:");
            sb.AppendLine("                    throw new CommandFailedException(");
            sb.AppendLine("                        $\"Invalid NamedBuildTarget '{value}'. Valid values: " +
                          string.Join(", ", targets) + "\",");
            sb.AppendLine("                        null);");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static List<string> CollectStaticTargets(INamedTypeSymbol type)
        {
            var targets = new List<string>();

            foreach (var member in type.GetMembers())
            {
                if (member.DeclaredAccessibility != Accessibility.Public)
                    continue;

                if (!member.IsStatic)
                    continue;

                if (IsObsolete(member))
                    continue;

                var memberTypeName = "";
                if (member is IPropertySymbol prop)
                {
                    memberTypeName = TypeSerializabilityChecker.GetFullMetadataName(prop.Type);
                }
                else if (member is IFieldSymbol field && field.IsReadOnly)
                {
                    memberTypeName = TypeSerializabilityChecker.GetFullMetadataName(field.Type);
                }
                else
                {
                    continue;
                }

                if (memberTypeName == "UnityEditor.Build.NamedBuildTarget")
                {
                    targets.Add(member.Name);
                }
            }

            return targets;
        }

        private static bool IsObsolete(ISymbol symbol)
        {
            return symbol.GetAttributes().Any(a =>
                a.AttributeClass != null &&
                TypeSerializabilityChecker.GetFullMetadataName(a.AttributeClass) ==
                "System.ObsoleteAttribute");
        }
    }
}
