name: Lint

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  dotnet-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore
        run: dotnet restore UniCli.sln
      - name: Check formatting
        run: dotnet format UniCli.sln --verify-no-changes --verbosity diagnostic
